from pymodbus.client.sync import ModbusTcpClient
from time import sleep

client = ModbusTcpClient('192.168.0.118', 5020)
client.write_coil(0, True)
sleep(1)
client.write_coil(1, True)
sleep(1)
client.write_coil(2, True)
sleep(1)
client.write_coil(3, True)
sleep(1)
client.write_coil(4, True)
sleep(1)
client.write_coil(5, True)
sleep(1)
client.write_coil(6, True)
sleep(1)
client.write_coil(7, True)
sleep(1)
client.write_coil(0, False)
sleep(1)
client.write_coil(1, False)
sleep(1)
client.write_coil(2, False)
sleep(1)
client.write_coil(3, False)
sleep(1)
client.write_coil(4, False)
sleep(1)
client.write_coil(5, False)
sleep(1)
client.write_coil(6, False)
sleep(1)
client.write_coil(7, False)
client.close()
